import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./header/header";
import Footer from "./footer/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased` } 
      >
        <div className="programming-particles"></div>
        <div className="programming-particles-2"></div>
        <div className="programming-particles-3"></div>
        <div className="programming-particles-4"></div>
        <div className="terminal-cursor"></div>
        <Header/>
        <div className="mx-auto w-full max-w-7xl ">
          {children}
        </div>
        <Footer/>
      </body>
    </html>
  );
}
