import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import Header from "./header/header";
import Footer from "./footer/footer";


const dmSans = DM_Sans({
  subsets: ['latin'],
  variable: '--font-dm-sans',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${dmSans.className} antialiased` } 
      >
        {/* Global programming particles */}
        <div className="programming-particles"></div>
        <div className="programming-particles-2"></div>
        <div className="programming-particles-3"></div>
        <div className="programming-particles-4"></div>
        <Header/>
        <div className="mx-auto w-full max-w-8xl">
          {children}
        </div>
        <Footer/>
      </body>
    </html>
  );
}
